Feature/issue 74 comment form controller view
vanmarcke/ocr_projet6_SnowTricks pull request #75
Opened 2022-02-11 13:53 UTC by vanmarcke

Issue (#74]

Creation of the add a comment form. Update for management to add a comment. Update of the details model of a figure (addition of the comment field + button)

2022-02-13 13:51 UTC, antoinetrouve requested changes

2022-02-13 13:51 UTC, antoinetrouve commented on src/Controller/FigureController.php
> +                $this->addFlash('danger', 'Erreur Système : veuillez ré-essayer');
Tu peux mettre le service de traduction symafony : https://symfony.com/doc/current/translation.html

2022-02-13 13:51 UTC, antoinetrouve commented on src/Manager/FigureManager.php
> +    /**
Revoir les commentaires

2022-02-13 13:51 UTC, antoinetrouve commented on src/Manager/FigureManager.php
> +        $comment->setSnowFigure($figure);
```suggestion
        $comment
            ->setSnowFigure($figure)
            ->setSnowUser($user)
            ->setCreatedAt(new DateTime()
        ;
```

2022-02-13 13:51 UTC, antoinetrouve commented on src/Manager/FigureManager.php
> +        $comment->setSnowUser($user);
```suggestion
```

2022-02-13 13:51 UTC, antoinetrouve commented on src/Manager/FigureManager.php
> +        $comment->setCreatedAt(new DateTime());
```suggestion
```

2022-02-13 13:51 UTC, antoinetrouve commented on src/Manager/FigureManagerInterface.php
> +interface FigureManagerInterface
C'est très bien d'avoir fait une interface. Cependant celle-ci est incomplète. 
    - public function getPublishedFigures(): array
    - public function getPublishedFiguresLimit(int $max): array
    - public function getPublishedNumFigure(int $max, int $numFigure): array
    - public function getComment(SnowFigure $snowFigure, int $offset): Paginator

2022-02-13 13:51 UTC, antoinetrouve commented on src/Controller/FigureController.php
> +    public function index(Request $request, FigureManager $figureManager, FigureManagerInterface $figureManagerInterface, SnowFigure $figure): Response
```suggestion
    public function index(Request $request, FigureManagerInterface $figureManager, SnowFigure $figure): Response
```

2022-02-13 13:51 UTC, antoinetrouve commented on src/Controller/FigureController.php
> +                $figureManagerInterface->newComment($comment, $figure, $user);
```suggestion
                $figureManager->newComment($comment, $figure, $user);
```

2022-02-14 07:39 UTC, vanmarcke commented on src/Manager/FigureManager.php
> +    /**
Done

2022-02-14 07:43 UTC, vanmarcke commented on src/Manager/FigureManager.php
> +        $comment->setSnowFigure($figure);
Done

2022-02-14 07:46 UTC, vanmarcke commented on src/Manager/FigureManager.php
> +        $comment->setSnowUser($user);
Done

2022-02-14 07:47 UTC, vanmarcke commented on src/Manager/FigureManager.php
> +        $comment->setCreatedAt(new DateTime());
Done

2022-02-14 08:22 UTC, vanmarcke commented on src/Controller/FigureController.php
> +    public function index(Request $request, FigureManager $figureManager, FigureManagerInterface $figureManagerInterface, SnowFigure $figure): Response
Done

2022-02-14 08:22 UTC, vanmarcke commented on src/Controller/FigureController.php
> +                $figureManagerInterface->newComment($comment, $figure, $user);
Done

2022-02-14 08:28 UTC, vanmarcke commented on src/Manager/FigureManagerInterface.php
> +interface FigureManagerInterface
Done

2022-02-14 08:54 UTC, vanmarcke commented on src/Controller/FigureController.php
> +                $this->addFlash('danger', 'Erreur Système : veuillez ré-essayer');
Point à voir lors de notre session de mentorat

2022-02-14 10:49 UTC, merged